<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<package format="1" xmlns="https://wiki.freecad.org/Package_Metadata">
  <name>AlumFrame</name>
  <description>Parametric aluminum extrusion frame generator with automatic BOM and dimension annotations.</description>
  <version>2.1.0</version>
  <date>2026-09-22</date>
  <maintainer email="gdbdzgd@gmail.com">gdbdzgd</maintainer>
  <license file="LICENSE">LGPL-2.1-or-later</license>
  <url type="repository" branch="main">https://github.com/gdbdzgd/AulmFrame</url>
  <url type="bugtracker">https://github.com/gdbdzgd/AulmFrame/issues</url>
  <icon>icons/frame_xpm.xpm</icon>

  <content>
    <workbench>
      <classname>AlumFrameWorkbench</classname>
      <subdirectory>./</subdirectory>
      <freecadmin>0.19</freecadmin>
      <tag>frame</tag>
      <tag>aluminum</tag>
    </workbench>
    <depend>Part</depend>
    <depend>Sketcher</depend>
  </content>

</package>
